### ISSUE TITLE
Error When Running EXO Commands

### ISSUE THREAD

**Issue by tld6764** [nlepagnez/ESI-PublicContent#12]
I am seeing the following error when executing the runbook:
**_Write-LogMessage : General : Error during data collection - System.Management.Automation.CommandNotFoundException: The term 'Get-Mailbox' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again._**
I am getting this for all Exchange-based commands in the runbook; the exchange module has been imported property. I have attached a copy of the runbook output.
The runbook is loading data to the log analytics; just not executing the EXO commands for some reason.
[JobOutput_1fa8d557-bb1a-4aaa-afb5-a8deb659d10f.txt](https://github.com/user-attachments/files/15888322/JobOutput_1fa8d557-bb1a-4aaa-afb5-a8deb659d10f.txt)

**Comment by B1129E5** [comment]
Hello

Could you please ensure that the account used by the azure automation is Global Reader and the API permissions are correctly assigned

**Comment by tld6764** [comment]
![2024-06-18 11_32_24-ESI-DataCollector - Microsoft Entra admin center and 5 more pages - Work - Micro](https://github.com/nlepagnez/ESI-PublicContent/assets/105518999/47fbe9bc-a3b0-4d50-b688-251ca13ba42e)
![2024-06-18 11_33_42-Global Reader - Microsoft Entra admin center and 5 more pages - Work - Microsoft](https://github.com/nlepagnez/ESI-PublicContent/assets/105518999/3f5aa8ee-d282-42b3-8f96-c8efb769082b)
I have verified both. Please see attached.

**Comment by B1129E5** [comment]
Hello

could you please check the module version for Az.Account and Exchange Online
Depending on your GUi Experience, it can be find here

- In Shared Resources/Modules
  - ![image](https://github.com/nlepagnez/ESI-PublicContent/assets/94830241/559bd4e9-2b1f-4a66-b4f7-03b264992226)
  - ![image](https://github.com/nlepagnez/ESI-PublicContent/assets/94830241/40c3869e-54b4-49ea-901f-4a5e649d787b)
- In Process Automation/Runtime Environment (Preview)
![image](https://github.com/nlepagnez/ESI-PublicContent/assets/94830241/9625c1bb-6b5f-4dfc-a804-99e16867f01a)
 -![image](https://github.com/nlepagnez/ESI-PublicContent/assets/94830241/734350f7-0a9d-4288-aebf-9c461edfd45c)
-![image](https://github.com/nlepagnez/ESI-PublicContent/assets/94830241/163de976-891c-4bdf-9926-b9b050f3ba6a)

**Comment by tld6764** [comment]
Well, I removed the runbook and managed identity and redeployed everything. Now its working. I guess I did something to it trying to upgrade it to version 7.6. I left everything as-is on the version that deployed from the connector page in Azure and its all working now?

**Comment by B1129E5** [comment]
Thanks for let us know.

Hope you'll enjoy the solution.

Karine




----------------------------------------------------------------------------------------------

Karine Sanguinet

CSA CyberSecurity

CISSP

Phone :  +33 1 57752870

Mobile : +33 6 64406987
***@***.******@***.***>

[MSFT_logo_Gray DE sized SIG1.png]

If you have any feedback about my work, please let either myself or my manager know at ***@***.******@***.***>





________________________________
