### ISSUE TITLE
isRunbook is evaluated with Get-AutomationVariable

### ISSUE THREAD

**Issue by SirFrancisDrake93** [nlepagnez/ESI-PublicContent#5]
On our Exchange Servers we got anytime the following error message:
Get-AutomationVariable: unrecognized guid format.

We figured out, that this was coming from $isRunbook beeing $true. This is evaluated at the beginning of the script by testing if the cmdlet "Get-AutomationVariable" exists. Unfortunately (and I don't know why) this cmdlet exists on our exchange server. So $isRunbook was set to $true and the behaviour of the script does not match the environment.

Setting $isRunbook statical to $false did fix the issue for us and we were able to assess our exchange environment.

Maybe you can have a look at the calculation of $isRunbook... Maybe set it to $false, if OP environment is selected?

Thanks for this great script and best regards,
Björn

**Comment by nlepagnez** [comment]
Hi Björn,

Effectively "Get-AutomationVariable" is normally a Cmdlet reserved to an Azure Automation Account execution, it's why we use that to determine if we are in a context of Automation Runbook execution or not.

We can't use the "OP/OL" environment as a criterion to know where the script is executed as we have a few customers that execute the collector script from an Azure Automation for Exchange On-Premise environment.

We will think in the next days about the better solution to answer your problem, perhaps by adding a "master" switch to force the execution environment in your case that is very specific.

We will keep you updated in this issue.

Thank you,
Nicolas Lepagnez

**Comment by nlepagnez** [comment]
The issue is corrected in the version 7.5.2.0 of the script, latest version can be found here : [ESI Collector Versions](https://github.com/nlepagnez/ESI-PublicContent/tree/main/Solutions/ESICollector)
